/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vehicle.main;

import vehicle.parkingcontroll.BikeForm;
import vehicle.parkingcontroll.CarForm;
import vehicle.parkingcontroll.VanForm;
import vehicle.parkingcontroll.WheelForm;

/**
 *
 * @author lmarcho
 */
public class GateForm extends javax.swing.JFrame {
       private BikeForm bike;
       private CarForm car;
       private VanForm van;
       private WheelForm wheel;
       int bikeCount=0;
       int carCount=0;
       int vanCount=0;
       int wheelCount=0;
    
    public GateForm() {
        initComponents();
         bike=new BikeForm();
         car=new CarForm();
         van=new VanForm();
         wheel=new WheelForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblGate = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        text1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        lblGate.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lblGate.setText("GATE");
        lblGate.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(lblGate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblGate)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jComboBox1.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Van", "Car", "Bike", "wheel" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        text1.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        text1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
         String vehicles =(String)jComboBox1.getSelectedItem();
         if(vehicles.equals("Van")){
             van.setVisible(true);
         }
         if(vehicles.equals("Bike")){
             bike.setVisible(true);
         }
         if(vehicles.equals("Car")){
             car.setVisible(true);
         }
         if(vehicles.equals("wheel")){
             wheel.setVisible(true);     
         }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text1ActionPerformed
        String vehicles =(String)jComboBox1.getSelectedItem();
         if(vehicles.equals("Van")){
             if (van.getNumber().equals("")) {
                 van.setNumber(vanCount+"");
             }else{
             van.setVisible(true);
             vanCount+=Integer.parseInt(text1.getText());
             van.setNumber(vanCount+"");
             }
         }
         if(vehicles.equals("Bike")){
             if (bike.getNumber().equals("")) {
                 bike.setNumber(bikeCount+"");
             }else{            
             bike.setVisible(true);
             bikeCount+=Integer.parseInt(text1.getText());
             bike.setNumber(bikeCount+"");
             }
         }
         if(vehicles.equals("Car")){
             if (car.getNumber().equals("")) {
                 car.setNumber(carCount+"");
             }else{
             car.setVisible(true);
             carCount+=Integer.parseInt(text1.getText());
             car.setNumber(carCount+"");
             }
         }
         if(vehicles.equals("wheel")){
             if (wheel.getNumber().equals("")) {
                 wheel.setNumber(wheelCount+"");
             }else{
             wheel.setVisible(true); 
             wheelCount+=Integer.parseInt(text1.getText());
             wheel.setNumber(wheelCount+"");   
             }
         }
    }//GEN-LAST:event_text1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GateForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblGate;
    private javax.swing.JTextField text1;
    // End of variables declaration//GEN-END:variables
}
